---
title: "Experiment 2 of 4"
output:
  html_document:
    toc: yes
    mathjax: default
    template: default
    theme: default
---

<style>
table, th, td {
    border: 1px grey;
    border-collapse: collapse;
    padding:2px 5px 2px 5px
}  
</style>

```{r setup, , echo=FALSE, cache=FALSE}
library(knitr)
knit_hooks$set(crop = hook_pdfcrop)
library(pander)
```

```{r showInstructions, echo=FALSE, cache=TRUE}
v = c("crisp", "crisp", "vague", "vague")
n = c('number', 'word', 'number', 'word')
e <- c("Choose the square with 6 dots", "Choose the square with the fewest dots", "Choose a square with about 10 dots", "Choose a square with few dots")
i = data.frame(v, n, e)
names(i) = c("vagueness", "number", "example instruction")
pander(i, justify=c('center', 'left', 'left'))
```

```{r showItems, echo=FALSE, cache=TRUE}
items = c(1,2,3,4,5,6,7,8)
i = data.frame(Item = c("1","2","3","4"),
               x = c("06:15:24", "16:25:34", "26:35:44", "36:45:54"))
names(i) = c('Item', 'Numbers of dots')
pander(i, justify=c('center', 'center'))
```

```{r loadLibraries, message=FALSE, echo=FALSE, cache=FALSE}
library(knitr); library(ggplot2); library(xtable); library(gridExtra); library(lme4); library(lmerTest);  library(data.table); library(dplyr); library(dtplyr); library(pander); library(LMERConvenienceFunctions); source('summarySEwithin2.R') 
```

In this experiment we did not count any response as an error, instead we coded them as expected, borderline, and extreme.

```{r getData, echo=TRUE}
rawdata <- read.delim('e2-data.txt')
```

```{r trimData, echo=TRUE}
tempdata <- perSubjectTrim.fnc(rawdata, response='RT', subject='Subject', trim = 2.5)$data
rtdata <- tempdata
bldata <- tempdata
```

```{r e2-rtplot, fig.width=7, fig.height=3.5, echo=FALSE, message=FALSE, dev='pdf', crop=TRUE}
rtdataplot1 <- summarySEwithin2(rtdata, measurevar="RT_log", withinvars=c("Condition", "Vagueness", "Number", "Item"), idvar="Subject")
rtdataplot1$Condition <- as.factor(paste(sep=':', rtdataplot1$Number, rtdataplot1$Vagueness))
rtplot=ggplot(rtdataplot1, aes(y=RT_logNormed, x=Item, group=Condition, fill=Vagueness)) +
  geom_line() +
  geom_errorbar(width=.2, aes(ymin=RT_log-ci, ymax=RT_log+ci)) +
  geom_point(size=2, col=1, aes(shape=Vagueness)) +
  scale_fill_grey(name="Vagueness", start=0, end=1) +
  scale_shape_manual(name="Vagueness", values=c(21,22)) +
  ggtitle("Response time") +
  ylab("Respone time (log (ms))") + 
  xlab("") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="top",
        aspect.ratio=1,
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        axis.text.x = element_text(angle = 15)) +
  facet_grid(~Number)
rtplot
```

```{r e2-blplot, fig.width=7, fig.height=3.5, echo=FALSE, dev='pdf'}
bldataplot1 <- summarySEwithin2(bldata, measurevar="isBorderline", withinvars=c("Vagueness", "Number", "Item"), idvar="Subject")
blplot=ggplot(bldataplot1, aes(y=isBorderlineNormed, x=Item, group=Vagueness, fill=Vagueness)) + 
  geom_line() +
  geom_point(size=2, col=1, aes(shape=Vagueness)) +
  geom_errorbar(aes(width=.25, ymin=isBorderlineNormed-ci, ymax=isBorderlineNormed+ci)) +
  scale_fill_grey(name="Vagueness", start=0.3, end=.7) +
  facet_wrap(nrow=1,~Number) +
  ggtitle("Borderline responses") +
  ylab("Proportion") + 
  xlab("") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="top", 
        aspect.ratio=1,
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        legend.key.size=unit(4, 'mm'))
blplot
```
```{r e2-blBarChart, fig.width=7, fig.height=3.5, echo=FALSE, dev='pdf'}
blBarChart = ggplot(bldata) +
  geom_bar(aes(response_category, group=Number:Vagueness, fill=Vagueness),
           position=position_dodge(width=NULL)) +
  scale_fill_grey() +
  xlab(NULL) +
  ggtitle('Borderline response distribution') +
  facet_grid(~Number) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="top", 
        aspect.ratio=1,
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        legend.key.size=unit(4, 'mm'))
blBarChart
```

```{r e2-combined-metrics-plot, echo=FALSE, dev='pdf'}
rtdataplot1 <- summarySEwithin2(rtdata,  measurevar="RT_log",  withinvars=c("Vagueness", "Number", "Item"), idvar="Subject")
bldataplot1 <- summarySEwithin2(bldata, measurevar="isBorderline", withinvars=c("Vagueness", "Number", "Item"), idvar="Subject")
rtdataplot1$metric = 'Response time (log ms)'
bldataplot1$metric = 'Borderline rate (proportion)'
rtdataplot1$score=rtdataplot1$RT_log;rtdataplot1$RT_log=NULL
bldataplot1$score=bldataplot1$isBorderline;bldataplot1$isBorderline=NULL
rtdataplot1$normed=rtdataplot1$RT_logNormed;rtdataplot1$RT_logNormed=NULL
bldataplot1$normed=bldataplot1$isBorderlineNormed;bldataplot1$isBorderlineNormed=NULL
combined=rbind(rtdataplot1,bldataplot1)
combined$metric=as.factor(combined$metric)
combined$metric=relevel(combined$metric, ref='Response time (log ms)')
combined$facet = paste(sep='',combined$metric,combined$Number)
combined$condition=paste(combined$Number,combined$Vagueness)
combinedplote2 = ggplot(data=combined, aes(y=normed, x=Item, group=condition, fill=Vagueness)) +
  xlab(NULL) + ylab(NULL) +
  geom_line() +
  geom_errorbar(width=.1, lty=1, col=1, aes(ymin=normed-ci, ymax=normed+ci)) +
  geom_point(size=3, col=1, aes(shape=Vagueness)) +
  facet_grid(metric~Number, scales='free_y') +
  scale_fill_grey(name="Vagueness", start=0, end=1) +
  scale_shape_manual(name="Vagueness", values=c(21,22)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="right", 
        aspect.ratio=1,
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        legend.key.size=unit(4, 'mm'))
combinedplote2
```

```{r rtlmer, cache=TRUE, echo=TRUE}
rtlmer = lmerTest::lmer(data=rtdata,
                        RT_log ~ c_Vag * c_Num + c_Itm +
                          (1 + c_Vag * c_Num + c_Itm | Subject))
```

```{r tableRTmodelSimple, results='asis', echo=FALSE, cache=FALSE}
print(
  xtable(
    summary(rtlmer)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model"),
  caption.placement="top", 
  type='html')
```

```{r sepLmerForNumeric, results='asis', cache=TRUE, echo=2}
numOnly <- subset(rtdata, subset=Number=='Numeric')
numOnlylm <- lmerTest::lmer(data=numOnly, RT_log ~ c_Vag + c_Itm + (1 + c_Vag + c_Itm | Subject))
print(
  xtable(
    summary(numOnlylm)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model: Numeric only"),
  caption.placement="top", 
  type='html')
```

```{r sepLmerForVerbal, results='asis', cache=TRUE, echo=2}
verbalOnly <- subset(rtdata, subset=Number=='Verbal')
verbalOnlylm <- lmerTest::lmer(data=verbalOnly, RT_log ~ c_Vag + c_Itm + (1 + c_Vag + c_Itm | Subject))
print(
  xtable(
    summary(verbalOnlylm)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model: Verbal only"),
  caption.placement="top", 
  type='html')
```

```{r bllmer, cache=TRUE, echo=TRUE}
bllmer = lme4::glmer(data=bldata,
                        isBorderline ~ c_Vag * c_Num + c_Itm +
                          (1 + c_Vag * c_Num + c_Itm | Subject),
                        family="binomial", control = glmerControl(optimizer = "bobyqa"))
```

```{r tableErrorModelsimple, results='asis', echo=FALSE, cache=F}
print(
  xtable(
    summary(bllmer)$coefficients,
    digits=c(0, 2, 2, 1, 3),
    caption="Error rates model"),
  caption.placement="top", 
  type='html')
```

